baseurl = "/"
disqusShortname = ""
enableEmoji = true
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
languageCode = "en-us"
paginate = 5
paginatePath = "page"
pygmentsCodefences = true
pygmentsUseClasses = true
relativeurls = true
theme = "base16"
title = "Riku's Blog"
watch = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = -200
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -200
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = -100
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = -50
#[[menu.main]]
#    name = "R posts"
#    url = "/categories/r"
#    weight = -49
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rikutakei"
# [[menu.main]]
#     name = "Twitter"
#     url = "https://twitter.com/rstudio"

[params]
    description = "A website built through Hugo and blogdown."
