baseurl = "/"
languageCode = "en-us"
title = "A Hugo website"
theme = "base16"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeurls = true
paginate = 2
paginatePath = "page"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -200
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = -100
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = -50
[[menu.main]]
    name = "R posts"
    url = "/categories/r"
    weight = -49
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = -150
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

